<a href="https://colab.research.google.com/github/kevinjjzhang/AppSales-Mobile/blob/master/contentBase_2023c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import numpy.ma as ma
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
#import tabulate
#from recsysNN_utils import *
#pd.set_option("display.precision", 1)
import pickle

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
print(tf.__version__)
from platform import python_version
print(python_version())

2.12.0
3.10.11


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip /content/drive/MyDrive/Colab/data1/df_u_a_l_r1.zip /content/drive/MyDrive/Colab/data1/df_u_a_l_r1.csv

Archive:  /content/drive/MyDrive/Colab/data1/df_u_a_l_r1.zip
caution: filename not matched:  /content/drive/MyDrive/Colab/data1/df_u_a_l_r1.csv


In [ ]:
import os
DATA_DIR = os.path
#print(DATA_DIR)
#print (os.path.abspath('.'))#获得当前工作目录
print (os.path.abspath(os.curdir))#获得当前工作目录
myfile ='/content/drive/MyDrive/Colab/data1/df_u_a_l_r1.csv'
df = pd.read_csv(myfile)# ndex_col=0)
df.rename(columns={'label_id':'labe_id'},inplace=True)
df.head(2)

/content


user_id  article_id  type_id  labe_id  menu_id  mi_id  mDate  rating
0        1           1        1        1       17      2      0       1
1        1           1        1        1       18      2      0       1

In [ ]:
df.info()

NameError: ignored

In [ ]:
#df2.rename(columns={'label_id':'labe_id'},inplace=True)
df2 = pd.get_dummies(df, columns=['labe_id','menu_id','type_id','mi_id']) #,dummy_na=True)

In [ ]:
del df

In [ ]:
df2.head(1)

user_id  article_id  mDate  rating  labe_id_1  labe_id_2  labe_id_3  \
0        1           1      0       1          1          0          0   

   labe_id_4  labe_id_5  labe_id_6  ...  mi_id_792  mi_id_817  mi_id_851  \
0          0          0          0  ...          0          0          0   

   mi_id_864  mi_id_865  mi_id_866  mi_id_915  mi_id_917  mi_id_918  mi_id_920  
0          0          0          0          0          0          0          0  

[1 rows x 262 columns]

In [ ]:
df_y_train = df2['rating']
df_user_train = df2.drop(columns=['article_id','rating'])
df_item_train = df2.drop(columns=['user_id','rating'])
df_user_train.loc[:,'mDate'] = 1 #强制训练偏好2023文章

In [ ]:
df_y_train = df2['rating']

In [ ]:
df_user_train = df2.drop(columns=['article_id','rating'])

In [ ]:
df_item_train = df2.drop(columns=['user_id','rating'])

In [ ]:
df_user_train.loc[:,'mDate'] = 1 #强制训练偏好2023文章

In [ ]:
len(list(df2))

163

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/df2.pkl"
file = open(dirs, 'wb')

# dump information to that file
pickle.dump(df2, file)

# close the file
file.close()


In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/df2.pkl"
df2 = pd.read_pickle(dirs)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16818782 entries, 0 to 16818781
Columns: 262 entries, user_id to mi_id_920
dtypes: int64(4), uint8(258)
memory usage: 4.5 GB


In [ ]:
#del df2

In [ ]:
df_user_train.head(1)

user_id  mDate  labe_id_1  labe_id_2  labe_id_3  labe_id_4  labe_id_5  \
0        1      1          1          0          0          0          0   

   labe_id_6  labe_id_7  labe_id_8  ...  type_id_10  type_id_11  type_id_12  \
0          0          0          0  ...           0           0           0   

   type_id_13  type_id_14  type_id_15  type_id_16  type_id_17  type_id_18  \
0           0           0           0           0           0           0   

   type_id_19  
0           0  

[1 rows x 161 columns]

In [ ]:
df_item_train.head(1)

article_id  mDate  labe_id_1  labe_id_2  labe_id_3  labe_id_4  labe_id_5  \
0           1      0          1          0          0          0          0   

   labe_id_6  labe_id_7  labe_id_8  ...  type_id_10  type_id_11  type_id_12  \
0          0          0          0  ...           0           0           0   

   type_id_13  type_id_14  type_id_15  type_id_16  type_id_17  type_id_18  \
0           0           0           0           0           0           0   

   type_id_19  
0           0  

[1 rows x 161 columns]

In [ ]:
item_features = list(df_item_train)
user_features = list(df_user_train)
user_train = np.array(df_user_train.values)
item_train = np.array(df_item_train.values)
y_train1 = np.array(df_y_train.values)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/item_features.pkl"
file = open(dirs, 'wb')

# dump information to that file
pickle.dump(item_features, file)

# close the file
file.close()

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/item_features.pkl"
item_features = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/user_features.pkl"
file = open(dirs, 'wb')

# dump information to that file
pickle.dump(user_features, file)

# close the file
file.close()

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/user_features.pkl"
user_features = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/user_train_q.pkl"
file = open(dirs, 'wb')

# dump information to that file
pickle.dump(user_train, file)

# close the file
file.close()

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/user_train_q.pkl"
user_train = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data/item_train_q.pkl"
item_train = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/y_train1_q.pkl"

y_train1 = pd.read_pickle(dirs)

In [ ]:
item_features[:4]

['article_id', 'mDate', 'labe_id_1', 'labe_id_2']

In [ ]:
user_features[:4]

['user_id', 'mDate', 'labe_id_1', 'labe_id_2']

In [ ]:
y_train1

array([1, 1, 2, ..., 2, 2, 2])

In [ ]:
df_item_train_p = df_item_train.groupby(['article_id']).sum()
df_item_train_p[df_item_train_p>0] = 1
df_item_train_p = df_item_train_p.reset_index()


In [ ]:
df_item_train_p.head(2)

article_id  mDate  labe_id_1  labe_id_2  labe_id_3  labe_id_4  labe_id_5  \
0           1      0          1          0          0          0          0   
1           3      1          0          1          0          0          0   

   labe_id_6  labe_id_7  labe_id_8  ...  type_id_10  type_id_11  type_id_12  \
0          0          0          0  ...           1           1           1   
1          0          0          0  ...           1           1           1   

   type_id_13  type_id_14  type_id_15  type_id_16  type_id_17  type_id_18  \
0           1           1           0           1           0           0   
1           1           1           1           1           1           0   

   type_id_19  
0           0  
1           1  

[2 rows x 154 columns]

In [ ]:
df_user_train_p =df_user_train.drop_duplicates()

In [ ]:
df_user_train_p.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 251998 entries, 0 to 526912
Columns: 154 entries, user_id to type_id_19
dtypes: int64(2), uint8(152)
memory usage: 42.3 MB


In [ ]:
num_user_features = user_train.shape[1] -1  
num_item_features = item_train.shape[1] -1
uvs = 1  # user genre vector start
ivs = 1  # item genre vector start
u_s = 1  # start of columns to use in training, user
i_s = 1 # # start of columns to use in training, items
print(f"num_user_features: {num_user_features}")
print(f"num_item_features: {num_item_features}")

print(f"Number of training vectors: {len(item_train)}")
print(f'item_train.shape:{item_train.shape}')
print(f'user_train.shape:{user_train.shape}')
print(f'y_train.shape:{y_train1.shape}')
print(f'user_features:{len(user_features),user_features}')
print(f'item_features:{len(item_features),item_features}')
#rint(f'item_vecs.shape:{item_vecs.shape}')

num_user_features: 153
num_item_features: 153
Number of training vectors: 526917
item_train.shape:(526917, 154)
user_train.shape:(526917, 154)
y_train.shape:(526917,)
user_features:(154, ['user_id', 'mDate', 'labe_id_1', 'labe_id_2', 'labe_id_3', 'labe_id_4', 'labe_id_5', 'labe_id_6', 'labe_id_7', 'labe_id_8', 'labe_id_9', 'labe_id_10', 'labe_id_11', 'labe_id_12', 'labe_id_13', 'labe_id_14', 'labe_id_15', 'labe_id_16', 'labe_id_17', 'labe_id_18', 'labe_id_19', 'labe_id_20', 'labe_id_21', 'labe_id_22', 'labe_id_23', 'labe_id_24', 'labe_id_25', 'labe_id_26', 'labe_id_27', 'labe_id_28', 'labe_id_29', 'labe_id_30', 'labe_id_31', 'labe_id_32', 'labe_id_33', 'labe_id_34', 'labe_id_35', 'labe_id_36', 'labe_id_37', 'labe_id_38', 'labe_id_39', 'labe_id_40', 'labe_id_41', 'labe_id_42', 'labe_id_43', 'labe_id_44', 'labe_id_45', 'labe_id_46', 'labe_id_47', 'labe_id_48', 'labe_id_49', 'labe_id_50', 'labe_id_51', 'labe_id_52', 'labe_id_53', 'labe_id_54', 'labe_id_55', 'labe_id_56', 'labe_id_57', 'la

In [ ]:
num_user_features = 153
num_item_features = 153
uvs = 1  # user genre vector start
ivs = 1  # item genre vector start
u_s = 1  # start of columns to use in training, user
i_s = 1 # # start of columns to use in training, items

In [ ]:
print(f"y_train1[:5]: {y_train1[:5]}")
print(y_train1.shape)

y_train1[:5]: [5. 5. 5. 5. 5.]
(1557864,)


In [ ]:
y_train_unscaled    = y_train1

In [ ]:
# scale training data
item_train_unscaled = item_train
user_train_unscaled = user_train
y_train_unscaled    = y_train1

scalerItem = StandardScaler()
scalerItem.fit(item_train)
item_train = scalerItem.transform(item_train)

scalerUser = StandardScaler()
scalerUser.fit(user_train)
user_train = scalerUser.transform(user_train)

scalerTarget = MinMaxScaler((-1, 1))
scalerTarget.fit(y_train1.reshape(-1, 1))
y_train = scalerTarget.transform(y_train1.reshape(-1, 1))
#ynorm_test = scalerTarget.transform(y_test.reshape(-1, 1))

print(np.allclose(item_train_unscaled, scalerItem.inverse_transform(item_train)))
print(np.allclose(user_train_unscaled, scalerUser.inverse_transform(user_train)))

True
True


In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/scalerUser_user.pkl"
scalerUser = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/scalerUser_user.pkl"
scalerUser = pd.read_pickle(dirs)

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/scalerTarget.pkl"
scalerTarget = pd.read_pickle(dirs)

FileNotFoundError: ignored

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data/y_train2.pkl"
y_train = pd.read_pickle(dirs)

In [ ]:
y_train1 = y_train

In [ ]:
y_train = y_train1

In [ ]:
# 最后全量时跳过
item_train, item_test = train_test_split(item_train, train_size=0.80, shuffle=True)  #random_state=1)
user_train, user_test = train_test_split(user_train, train_size=0.80, shuffle=True)
y_train, y_test    = train_test_split(y_train1,  train_size=0.80, shuffle=True)
print(f"article/item training data shape: {item_train.shape}")
print(f"article/item test data shape: {item_test.shape}")

article/item training data shape: (421533, 154)
article/item test data shape: (105384, 154)


In [ ]:
len(y_train)

421533

In [ ]:
y_train, y_test    = train_test_split(y_train1,  train_size=0.80, shuffle=True)
print(f"article/item training data shape: {item_train.shape}")
print(f"article/item test data shape: {item_test.shape}")

article/item training data shape: (215824, 154)
article/item test data shape: (53956, 154)


In [ ]:
#sigmoid

In [ ]:
num_outputs = 128
user_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    #tf.keras.layers.Dense(128, activation='relu'),
    #tf.keras.layers.Dense(128, activation='relu'),    
    #tf.keras.layers.Dense(64, activation='relu'),
    #tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(num_outputs)
])

item_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    #tf.keras.layers.Dense(256, activation='relu'),
    #tf.keras.layers.Dense(128, activation='relu'),
    #tf.keras.layers.Dense(64, activation='relu'),
    #tf.keras.layers.Dense(64, activation='relu'),
    #    
    tf.keras.layers.Dense(num_outputs)
])

# create the user input and point to the base network
input_user = tf.keras.layers.Input(shape=(num_user_features))
vu = user_NN(input_user)
vu = tf.linalg.l2_normalize(vu, axis=1)

# create the item input and point to the base network
input_item = tf.keras.layers.Input(shape=(num_item_features))
vm = item_NN(input_item)
vm = tf.linalg.l2_normalize(vm, axis=1)

# compute the dot product of the two vectors vu and vm
output = tf.keras.layers.Dot(axes=1)([vu, vm])

# specify the inputs and output of the model
model = tf.keras.Model([input_user, input_item], output)

model.summary()

Model: "model_13"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_27 (InputLayer)          [(None, 153)]        0           []                               
                                                                                                  
 input_28 (InputLayer)          [(None, 153)]        0           []                               
                                                                                                  
 sequential_26 (Sequential)     (None, 128)          243072      ['input_27[0][0]']               
                                                                                                  
 sequential_27 (Sequential)     (None, 128)          243072      ['input_28[0][0]']               
                                                                                           

In [ ]:
tf.random.set_seed(1)
cost_fn = tf.keras.losses.MeanSquaredError()
#cost_fn = tf.keras.losses.MeanAbsoluteError()
opt = keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss=cost_fn)

In [ ]:
user_train[:, u_s:].shape

(1337493, 153)

In [ ]:
item_train[:, i_s:].shape

(1188883, 153)

In [ ]:
y_train.shape

(1188883,)

In [ ]:
tf.random.set_seed(1)
model.fit([user_train[:, u_s:], item_train[:, i_s:]], y_train, epochs=30)

Epoch 1/30
16467/16467 [==============================] - 232s 14ms/step - loss: 0.3857
Epoch 2/30
16467/16467 [==============================] - 223s 14ms/step - loss: 0.3820
Epoch 3/30
16467/16467 [==============================] - 221s 13ms/step - loss: 0.3809
Epoch 4/30
16467/16467 [==============================] - 224s 14ms/step - loss: 0.3802
Epoch 5/30
16467/16467 [==============================] - 223s 14ms/step - loss: 0.3798
Epoch 6/30
16467/16467 [==============================] - 223s 14ms/step - loss: 0.3794
Epoch 7/30
16467/16467 [==============================] - 222s 13ms/step - loss: 0.3793
Epoch 8/30
16467/16467 [==============================] - 224s 14ms/step - loss: 0.3790
Epoch 9/30
16467/16467 [==============================] - 222s 14ms/step - loss: 0.3788
Epoch 10/30
16467/16467 [==============================] - 227s 14ms/step - loss: 0.3786
Epoch 11/30
16467/16467 [==============================] - 226s 14ms/step - loss: 0.3785
Epoch 12/30
16467/16467 [=====

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/model.pkl"
file = open(dirs, 'wb')

# dump information to that file
pickle.dump(model, file)

# close the file
file.close()

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data1/model.pkl"
model = pd.read_pickle(dirs)

In [ ]:
user_test

NameError: ignored

In [ ]:
model.evaluate([user_test[:, u_s:], item_test[:, i_s:]], y_test) # old

9289/9289 [==============================] - 22s 2ms/step - loss: 1.7723


1.7723411321640015

In [ ]:
model.evaluate([user_test[:, u_s:], item_test[:, i_s:]], y_test) # 80%

3294/3294 [==============================] - 7s 2ms/step - loss: 0.8725


0.872456967830658

In [ ]:
model.evaluate([user_test[:, u_s:], item_test[:, i_s:]], y_test) 

3294/3294 [==============================] - 13s 4ms/step - loss: 0.8725


0.8724580407142639

In [ ]:
model.evaluate([user_test[:, u_s:], item_test[:, i_s:]], y_test) 

9289/9289 [==============================] - 29s 3ms/step - loss: 0.5064


0.5064346790313721

In [ ]:
df_active = pd.read_csv(r"/content/drive/MyDrive/Colab/data/df_active3.csv", dtype='int64')

In [ ]:
df_active.drop_duplicates(subset=['user_id'], keep='first', inplace=True)

In [ ]:
df_active = df_active[df_active["user_id"].isin(df_user_train.user_id.unique())]

In [ ]:
df_active

user_id
0         5639
1          707
2         1585
3         4133
4         2392
...        ...
11170    15130
11171      198
11172     6548
11173    21558
11174    17315

[11175 rows x 1 columns]

In [ ]:
int(len(df_active)/2)

5587

In [ ]:
lst_user_sample = df2.user_id.sample(int(len(df_active)/2),replace=False)

In [ ]:
lst_user_sample.head(2)

938712    3880
595497     548
Name: user_id, dtype: int64

In [ ]:
df_active.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11175 entries, 0 to 11174
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  11175 non-null  int64
dtypes: int64(1)
memory usage: 174.6 KB


In [ ]:
%%capture --no-display
def gen_user_vecs(user_vec, num_items):
    """ given a user vector return:
        user predict maxtrix to match the size of item_vecs """
    user_vecs = np.tile(user_vec, (num_items, 1))
    return user_vecs

temp_df = pd.DataFrame()
i = 1

for user_id in df_active.user_id:   #lst_user_sample: #[:2]:
    #print(user_id)
    #此用户特征
    
    df_user_vec = df_user_train_p[df_user_train_p['user_id']==user_id ]
    df_user_vec = df_user_vec.groupby('user_id').sum()
    df_user_vec[df_user_vec>0] = 1
    if df_user_vec.empty:
      continue

    user_vec = df_user_vec.reset_index().values
    #此用户看过的文章
    lst_readed_article = df2[df2['user_id'] == user_id]['article_id'].unique()
    #此用户没有看过的文章特征
    df_item_train_p1 = df_item_train_p[~df_item_train_p['article_id'].isin(lst_readed_article)]
    #df_item_train_p1 = df_item_train_p.copy()
    item_vecs = df_item_train_p1.values
    user_vecs = gen_user_vecs(user_vec,len(item_vecs))
    suser_vecs = scalerUser.transform(user_vecs)
    sitem_vecs = scalerItem.transform(item_vecs)
    y_p = model.predict([suser_vecs[:, u_s:], sitem_vecs[:, i_s:]])
      
    sorted_index = np.argsort(-y_p,axis=0).reshape(-1).tolist()  #negate to get largest rating first   
    ##sorted_ypu   = y_p[sorted_index]
    sorted_items = item_vecs[sorted_index]  #using unscaled vectors for display
    #print(int(sorted_items[0:2][0][0]))
    dic1 = {}
    dic1['user_id'] = user_id
    dic1['article_id1'] = int(sorted_items[0:2][0][0])
    dic1['article_id2'] = int(sorted_items[0:2][1][0])
    #dic1 = {'user_id':user_id,'article_id1':int(sorted_items[0:2][0][0])}
    #dic2 = {'user_id':user_id,'article_id2':int(sorted_items[0:2][1][0])}
    #print(dic1)
    temp_df = pd.concat([temp_df,pd.DataFrame(dic1,index = [0])],ignore_index=True)
    if i %3000:
      print(str(i))
    i+=1
    del df_user_vec
    del df_item_train_p1
print("ok")

流式输出内容被截断，只能显示最后 5000 行内容。
43/43 [==============================] - 0s 5ms/step
3620
43/43 [==============================] - 0s 5ms/step
3621
43/43 [==============================] - 0s 5ms/step
3622
43/43 [==============================] - 0s 4ms/step
3623
41/41 [==============================] - 0s 4ms/step
3624
43/43 [==============================] - 0s 5ms/step
3625
41/41 [==============================] - 0s 4ms/step
3626
43/43 [==============================] - 0s 5ms/step
3627
43/43 [==============================] - 0s 4ms/step
3628
43/43 [==============================] - 0s 5ms/step
3629
43/43 [==============================] - 0s 4ms/step
3630
43/43 [==============================] - 0s 4ms/step
3631
43/43 [==============================] - 0s 5ms/step
3632
43/43 [==============================] - 0s 5ms/step
3633
43/43 [==============================] - 0s 4ms/step
3634
43/43 [==============================] - 0s 5ms/step
3635
43/43 [==============================] - 0s 5

In [ ]:
temp_df.to_csv(r"/content/drive/MyDrive/Colab/data1/df_result2.csv", index=False)

In [ ]:
temp_df.head()

user_id  article_id1  article_id2
0     5639         2879         3596
1      707         3589         3623
2     1585         2746         3752
3     4133         3592         3594
4     2392         2746         2992

In [ ]:
temp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6119 entries, 0 to 6118
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      6119 non-null   int64
 1   article_id1  6119 non-null   int64
 2   article_id2  6119 non-null   int64
dtypes: int64(3)
memory usage: 143.5 KB


In [ ]:
for user_id in lst_user_sample:
    #print(user_id)
    #此用户特征
    df_user_vec = df_user_train_p[df_user_train_p['user_id']==user_id ]
    if df_user_vec.empty:      
      print(user_id)

In [ ]:
temp_df = pd.DataFrame()

for user_id in lst_user_sample:
    #print(user_id)
    df_user_vec = df_user_train_p[df_user_train_p['user_id']==user_id ]
    df_user_vec = df_user_vec.groupby('user_id').sum()
    df_user_vec[df_user_vec>0] = 1
    user_vec = df_user_vec.reset_index().values
    lst_readed_article = df2[df2['user_id'] == user_id]['article_id'].unique()
    df_item_train_p1 = df_item_train_p[~df_item_train_p['article_id'].isin(lst_readed_article)]
    item_vecs = df_item_train_p1.values
    user_vecs = gen_user_vecs(user_vec,len(item_vecs))
    suser_vecs = scalerUser.transform(user_vecs)
    sitem_vecs = scalerItem.transform(item_vecs)
    y_p = model.predict([suser_vecs[:, u_s:], sitem_vecs[:, i_s:]])
      
    sorted_index = np.argsort(-y_p,axis=0).reshape(-1).tolist()  #negate to get largest rating first
    #sorted_ypu   = y_p[sorted_index]
    sorted_items = item_vecs[sorted_index]  #using unscaled vectors for display
    #print(sorted_items)
    #sorted_items = scalerItem.inverse_transform(sorted_items)
    #print(sorted_items.shape)
    sorted_items = int(sorted_items[:1][0][0])
    #print(sorted_items)
    #temp_df = pd.concat([temp_df,pd.DataFrame({'user_id':user_id,'article_id':sorted_items})],ignore_index=True)
    dic1 = {'user_id':user_id,'article_id':sorted_items}
    temp_df = pd.concat([temp_df,pd.DataFrame(dic1,index = [0])],ignore_index=True)

3041
41/41 [==============================] - 0s 7ms/step
445
41/41 [==============================] - 0s 5ms/step
2685
41/41 [==============================] - 0s 4ms/step
103
37/37 [==============================] - 0s 4ms/step
930
40/40 [==============================] - 0s 4ms/step
1644
41/41 [==============================] - 0s 4ms/step
1996
40/40 [==============================] - 0s 5ms/step
1135
40/40 [==============================] - 0s 5ms/step
2685
41/41 [==============================] - 0s 5ms/step
2139
41/41 [==============================] - 0s 4ms/step
768
39/39 [==============================] - 0s 4ms/step
798
39/39 [==============================] - 0s 4ms/step
819
37/37 [==============================] - 0s 5ms/step
721
39/39 [==============================] - 0s 4ms/step
1925
41/41 [==============================] - 0s 4ms/step
2049
37/37 [==============================] - 0s 4ms/step
133
42/42 [==============================] - 0s 4ms/step
283
41/41 [===========

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data/result.csv"
temp_df.to_csv(dirs, index = False)

In [ ]:
lst_user_sample

380569     3041
1053408     445
488653     2685
1245323     103
332930      930
           ... 
567578     1094
725097      281
669086      464
665848     1350
599682     2453
Name: user_id, Length: 200, dtype: int64

In [ ]:
temp_df

user_id  article_id1  article_id2
0        3880          350          121
1         548          350          121
2         801          350          121
3        2373          350          121
4        1746          350          121
...       ...          ...          ...
5582      286          350          121
5583     2565          350          121
5584     1945          121         1307
5585     2539          350          121
5586     2128          350          121

[5587 rows x 3 columns]

# New Section

In [ ]:
user_id = 4442
df_user_vec = df_user_train_p[df_user_train_p['user_id']==user_id ]
df_user_vec = df_user_vec.groupby('user_id').sum()
df_user_vec[df_user_vec>0] = 1
user_vec = df_user_vec.reset_index().values

In [ ]:

user_vec

array([[4442,    0,    0,    1,    1,    1,    1,    0,    1,    0,    1,
           0,    0,    0,    0,    0,    0,    1,    1,    1,    0,    0,
           0,    1,    0,    1,    0,    0,    0,    0,    1,    0,    1,
           0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           1,    0,    0,    0,    0,    1,    0,    1,    0,    0,    0,
           0,    0,    0,    1,    0,    1,    0,    0,    1,    1,    0,
           1,    0,    0,    1,    0,    0,    0,    0,    1,    0,    1,
           0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    1, 

In [ ]:
item_vecs = df_item_train_p.values
user_vecs = gen_user_vecs(user_vec,len(item_vecs))

In [ ]:
item_vecs.shape

(1347, 151)

In [ ]:
user_vecs.shape

(1347, 149)

In [ ]:
#user_vecs = df_user_train_p.values
item_vecs = df_item_train_p.values
user_vecs = gen_user_vecs(user_vec,len(item_vecs))

print(user_vecs.shape)
print(item_vecs.shape)
suser_vecs = user_vecs
sitem_vecs = item_vecs

# scale our user and item vectors
#suser_vecs = scalerUser.transform(user_vecs)
#sitem_vecs = scalerItem.transform(item_vecs)

# make a prediction
y_p = model.predict([suser_vecs[:, u_s:], sitem_vecs[:, i_s:]])
print(y_p.shape)

(1347, 149)
(1347, 151)
43/43 [==============================] - 0s 2ms/step
(1347, 1)


In [ ]:
sorted_index = np.argsort(-y_p,axis=0).reshape(-1).tolist()  #negate to get largest rating first
sorted_ypu   = y_p[sorted_index]
sorted_items = item_vecs[sorted_index]  #using unscaled vectors for display
sorted_user  = user_vecs[sorted_index]

In [ ]:


# unscale y prediction 
y_pu = scalerTarget.inverse_transform(y_p)

# sort the results, highest prediction first


In [ ]:
sorted_index[:4]

[321, 1170, 133, 932]

In [ ]:
sorted_ypu[:4]

array([[1.0000002],
       [1.0000002],
       [1.0000001],
       [1.0000001]], dtype=float32)

In [ ]:
sorted_items[:4][0]

array([427.,  35.,   3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   1.,   1.,   1.,   1.,   1.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   1.,   

In [ ]:
sorted_user

In [ ]:
print_pred_movies(sorted_ypu, sorted_items, movie_dict, maxcount = 10)

In [ ]:
import joblib 

In [ ]:
dirs = r"/content/drive/MyDrive/Colab/data/model2.pkl"
joblib.dump(model, dirs )

['/content/drive/MyDrive/Colab/data/model2.pkl']

In [ ]:
item_train

array([[-0.21370717, -0.26385067, -0.42731332, ..., -0.00847169,
        -0.00410926, -0.00355872],
       [ 2.06172291, -0.26385067,  2.34020322, ..., -0.00847169,
        -0.00410926, -0.00355872],
       [-0.18897423, -0.26385067, -0.42731332, ..., -0.00847169,
        -0.00410926, -0.00355872],
       ...,
       [ 2.38325108, -0.26385067, -0.42731332, ..., -0.00847169,
        -0.00410926, -0.00355872],
       [-0.3785934 , -0.26385067, -0.42731332, ..., -0.00847169,
        -0.00410926, -0.00355872],
       [-0.41981496, -0.26385067, -0.42731332, ..., -0.00847169,
        -0.00410926, -0.00355872]])

In [ ]:
# 最后全量时跳过
item_train, item_test = train_test_split(item_train, train_size=0.90, shuffle=True, random_state=1)
user_train, user_test = train_test_split(user_train, train_size=0.90, shuffle=True, random_state=1)
y_train, y_test    = train_test_split(y_train1,  train_size=0.90, shuffle=True, random_state=1)
print(f"article/item training data shape: {item_train.shape}")
print(f"article/item test data shape: {item_test.shape}")

article/item training data shape: (639593, 235)
article/item test data shape: (71066, 235)


In [ ]:
df_4p = df_all.sample(1200,random_state=1)

In [ ]:
len(df_4p.userId.unique())

922

In [ ]:
df_all.sample(1)

userId  articleId            memberId  count  mean  nb_months  know  \
1435880    5498        743  981148642884718592     26   1.0         57     1   

         uni           article_id  raiting  ...  topic_10  topic_11  topic_12  \
1435880    1  1523501372492742656        1  ...         0         0         0   

         topic_13  topic_14  topic_15  topic_16  topic_17  topic_18  topic_19  
1435880         0         0         0         0         0         0         0  

[1 rows x 373 columns]

In [ ]:
user_id = 1355

In [ ]:
df_item_train_p = df_item_train.drop_duplicates()

In [ ]:
df_item_train_p.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3859 entries, 0 to 429556
Columns: 245 entries, article_id to label_id_244
dtypes: int64(1), uint8(244)
memory usage: 979.8 KB


In [ ]:
df_all_p =df_all[df_all["userId"] == 5498	]

(4, 369)
(4, 363)
1/1 [==============================] - 0s 141ms/step
(4, 1)


In [ ]:
sorted_ypu

array([[1.5882304],
       [1.5882304],
       [1.3128767],
       [1.2027172]], dtype=float32)

In [ ]:
sorted_ypu

array([[1.5882304],
       [1.5882304],
       [1.3128767],
       [1.2027172]], dtype=float32)

In [ ]:
sorted_items

array([[ 734,    0,    0, ...,    0,    0,    0],
       [ 743,    0,    0, ...,    0,    0,    0],
       [ 585,    0,    0, ...,    0,    0,    0],
       [1233,    0,    0, ...,    0,    0,    0]])

In [ ]:
def pprint_train(x_train, features, vs, u_s, maxcount=5, user=True):
    """ Prints user_train or item_train nicely """
    if user:
        flist = [".0f", ".0f", ".1f",
                 ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f", ".1f"]
    else:
        flist = [".0f", ".0f", ".1f", 
                 ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f", ".0f"]

    head = features[:vs]
    if vs < u_s: print("error, vector start {vs} should be greater then user start {u_s}")
    for i in range(u_s):
        head[i] = "[" + head[i] + "]"
    genres = features[vs:]
    hdr = head + genres
    disp = [split_str(hdr, 5)]
    count = 0
    for i in range(0, x_train.shape[0]):
        if count == maxcount: break
        count += 1
        disp.append([x_train[i, 0].astype(int),
                     x_train[i, 1].astype(int),
                     x_train[i, 2].astype(float),
                     *x_train[i, 3:].astype(float)
                    ])
    table = tabulate.tabulate(disp, tablefmt='html', headers="firstrow", floatfmt=flist, numalign='center')
    return table


def split_str(ifeatures, smax):
    ''' split the feature name strings to tables fit '''
    ofeatures = []
    for s in ifeatures:
        if not ' ' in s:  # skip string that already have a space
            if len(s) > smax:
                mid = int(len(s)/2)
                s = s[:mid] + " " + s[mid:]
        ofeatures.append(s)
    return ofeatures
    

def print_pred_movies(y_p, item, movie_dict, maxcount=10):
    """ print results of prediction of a new user. inputs are expected to be in
        sorted order, unscaled. """
    count = 0
    disp = [["y_p", "movie id", "rating ave", "title", "genres"]]

    for i in range(0, y_p.shape[0]):
        if count == maxcount:
            break
        count += 1
        movie_id = item[i, 0].astype(int)
        disp.append([np.around(y_p[i, 0], 1), item[i, 0].astype(int), np.around(item[i, 2].astype(float), 1),
                     movie_dict[movie_id]['title'], movie_dict[movie_id]['genres']])

    table = tabulate.tabulate(disp, tablefmt='html', headers="firstrow")
    return table

def gen_user_vecs(user_vec, num_items):
    """ given a user vector return:
        user predict maxtrix to match the size of item_vecs """
    user_vecs = np.tile(user_vec, (num_items, 1))
    return user_vecs

# predict on  everything, filter on print/use
def predict_uservec(user_vecs, item_vecs, model, u_s, i_s, scaler):
    """ given a scaled user vector, does the prediction on all movies in scaled print_item_vecs returns
        an array predictions sorted by predicted rating,
        arrays of user and item, sorted by predicted rating sorting index
    """
    y_p = model.predict([user_vecs[:, u_s:], item_vecs[:, i_s:]])
    y_pu = scaler.inverse_transform(y_p)

    if np.any(y_pu < 0):
        print("Error, expected all positive predictions")
    sorted_index = np.argsort(-y_pu, axis=0).reshape(-1).tolist()  #negate to get largest rating first
    sorted_ypu   = y_pu[sorted_index]
    sorted_items = item_vecs[sorted_index]
    sorted_user  = user_vecs[sorted_index]
    return(sorted_index, sorted_ypu, sorted_items, sorted_user)
                
def get_user_vecs(user_id, user_train, item_vecs, user_to_genre):
    """ given a user_id, return:
        user train/predict matrix to match the size of item_vecs
        y vector with ratings for all rated movies and 0 for others of size item_vecs """

    if not user_id in user_to_genre:
        print("error: unknown user id")
        return None
    else:
        user_vec_found = False
        for i in range(len(user_train)):
            if user_train[i, 0] == user_id:
                user_vec = user_train[i]
                user_vec_found = True
                break
        if not user_vec_found:
            print("error in get_user_vecs, did not find uid in user_train")
        num_items = len(item_vecs)
        user_vecs = np.tile(user_vec, (num_items, 1))

        y = np.zeros(num_items)
        for i in range(num_items):  # walk through movies in item_vecs and get the movies, see if user has rated them
            movie_id = item_vecs[i, 0]
            if movie_id in user_to_genre[user_id]['movies']:
                rating = user_to_genre[user_id]['movies'][movie_id]
            else:
                rating = 0
            y[i] = rating
    return(user_vecs, y)

def get_item_genres(item_gvec, genre_features):
    ''' takes in the item's genre vector and list of genre names
    returns the feature names where gvec was 1 '''
    offsets = np.nonzero(item_gvec)[0]
    genres = [genre_features[i] for i in offsets]
    return genres


def print_existing_user(y_p, y, user, items, ivs, uvs, movie_dict, maxcount=10):
    """ print results of prediction for a user who was in the database.
        Inputs are expected to be in sorted order, unscaled.
    """
    count = 0
    disp = [["y_p", "y", "user", "user genre ave", "movie rating ave", "movie id", "title", "genres"]]
    count = 0
    for i in range(0, y.shape[0]):
        if y[i, 0] != 0:  # zero means not rated
            if count == maxcount:
                break
            count += 1
            movie_id = items[i, 0].astype(int)

            offsets = np.nonzero(items[i, ivs:] == 1)[0]
            genre_ratings = user[i, uvs + offsets]
            disp.append([y_p[i, 0], y[i, 0],
                         user[i, 0].astype(int),      # userid
                         np.array2string(genre_ratings, 
                                         formatter={'float_kind':lambda x: "%.1f" % x},
                                         separator=',', suppress_small=True),
                         items[i, 2].astype(float),    # movie average rating
                         movie_id,
                         movie_dict[movie_id]['title'],
                         movie_dict[movie_id]['genres']])

    table = tabulate.tabulate(disp, tablefmt='html', headers="firstrow", floatfmt=[".1f", ".1f", ".0f", ".2f", ".1f"])
    return table

In [ ]:
import numpy as np
#保存为npy类型
np.save('文件的名字.npy',your_np_arr)
#npy的读取
your_np_arr = np.load('文件的名字.npy') https://www.bilibili.com/read/cv16080995 

In [ ]:
type(sorted_ypu)

numpy.ndarray

In [ ]:
pd.DataFrame(sorted_items).to_csv(r"/content/drive/MyDrive/Colab/data/sorted_items1.csv")

In [ ]:
pd.DataFrame(sorted_ypu).to_csv(r"/content/drive/MyDrive/Colab/data/sorted_ypu1.csv")

In [ ]:
pd.DataFrame(sorted_index).to_csv(r"/content/drive/MyDrive/Colab/data/sorted_index1.csv")

In [ ]:
user_vec

In [ ]:
pd.DataFrame(user_vec).to_csv(r"/content/drive/MyDrive/Colab/data/user_vec1.csv")

In [ ]:
pd.DataFrame(item_vecs).to_csv(r"/content/drive/MyDrive/Colab/data/item_vecs1.csv")